### ISSUE TITLE
SegWit: when will SW support be ready?

### ISSUE THREAD

**Issue by losh11** [voisine/breadwallet-ios#400]
Bitcoin Core 0.13.1 has been released, and SegWit activation will happen soon after 15th November 2016.

**Comment by voisine** [comment]
I've implemented segwit (mostly) here: https://github.com/breadwallet/breadwallet-core/tree/segwit

We are working on an app rewrite in swift3 using breadwallet-core, which is what breadwallet-android also uses. We don't want to cut over immediately when it activates, we want time to do mainnet testing ourselves and gain confidence that it's safe even for significant funds. The timing should work well for Q1.

**Comment by luishmelo** [comment]
So... When is this going to merge with the master?

**Comment by CikeQiu** [comment]
So... When is this going to merge with the master?
