### ISSUE TITLE
Unable to enter ip-address for manual node on German iPhone

### ISSUE THREAD

**Issue by raumi75** [voisine/breadwallet-ios#459]
The prompt for entering the IP-Address shows a keyboard with a comma instead of a period, so I can't enter a valid IP4-Address on a German language iPhone. Comma is the default decimal delimiter in Germany (and probably other countries)

Expected behavior: display a keyboard with a period key or automatically convert the comma to period.

**Comment by jkandzi** [comment]
fixed by #462 😇
